mutation CreateGoogleMailSearch(
  $account: ID!
  $params: GoogleMailSearchParams!
) {
  createGoogleMailSearch(account: $account, params: $params) {
    id
    name
    query
    dueOffset
    url
  }
}

mutation EditGoogleMailSearch($id: ID!, $params: GoogleMailSearchParams!) {
  editGoogleMailSearch(id: $id, params: $params) {
    id
    name
    query
    dueOffset
    url
  }
}

mutation DeleteGoogleMailSearch($id: ID!) {
  deleteGoogleMailSearch(id: $id)
}
