query ListGoogleAccounts {
  user {
    id
    googleAccounts {
      id
      email
      avatar
      loginUrl
      mailSearches {
        id
        name
        query
        url
      }
    }
  }
}

query RequestLoginUrl {
  googleLoginUrl
}

mutation CreateGoogleMailSearch($account: ID!, $params: GoogleMailSearchParams!) {
  createGoogleMailSearch(account: $account, params: $params) {
    id
    name
    query
    url
  }
}
