query ListBugzillaAccounts {
  user {
    bugzillaAccounts {
      id
      name
      icon
      url
    }
  }
}

mutation CreateBugzillaAccount($name: String!, $url: String!, $username: String!, $password: String) {
  createBugzillaAccount(name: $name, url: $url, username: $username, password: $password) {
    id
    name
    icon
    url
  }
}

mutation SetItemTaskType($item: ID!, $taskType: String!) {
  setItemTaskType(item: $item, taskType: $taskType)
}
