query ListBugzillaAccounts {
  user {
    bugzillaAccounts {
      id
      name
      icon
      url
      searches {
        id
        name
        type
        query
        url
      }
    }
  }
}

mutation CreateBugzillaAccount($params: BugzillaAccountParams!) {
  createBugzillaAccount(params: $params) {
    id
    name
    icon
    url
    searches {
      id
      name
      type
      query
      url
    }
  }
}

mutation CreateBugzillaSearch($account: ID!, $params: BugzillaSearchParams!) {
  createBugzillaSearch(account: $account, params: $params) {
    id
    name
    type
    query
    url
  }
}

mutation SetItemTaskType($item: ID!, $taskType: String!) {
  setItemTaskType(item: $item, taskType: $taskType)
}
