query ListJiraAccounts {
  user {
    id
    jiraAccounts {
      id
      serverName
      userName
      url
      email
      apiToken
      searches {
        id
        name
        query
        url
      }
    }
  }
}

mutation CreateJiraAccount($params: JiraAccountParams!) {
  createJiraAccount(params: $params) {
    id
    serverName
    userName
    url
    email
    apiToken
    searches {
      id
      name
      query
      url
    }
  }
}

mutation DeleteJiraAccount($account: ID!) {
  deleteJiraAccount(account: $account)
}

mutation CreateJiraSearch($account: ID!, $params: JiraSearchParams!) {
  createJiraSearch(account: $account, params: $params) {
    id
    name
    query
    url
  }
}

mutation DeleteJiraSearch($id: ID!) {
  deleteJiraSearch(search: $id)
}
