query ListGithubAccounts {
  user {
    id
    githubAccounts {
      id
      user
      avatar
      loginUrl
      searches {
        id
        name
        query
        dueOffset
        url
      }
    }
  }
}

query RequestLoginUrl {
  githubLoginUrl
}

mutation CreateGithubSearch($account: ID!, $params: GithubSearchParams!) {
  createGithubSearch(account: $account, params: $params) {
    id
    name
    query
    dueOffset
    url
  }
}

mutation EditGithubSearch($id: ID!, $params: GithubSearchParams!) {
  editGithubSearch(search: $id, params: $params) {
    id
    name
    query
    dueOffset
    url
  }
}

mutation DeleteGithubSearch($id: ID!) {
  deleteGithubSearch(search: $id)
}
