query ListPhabricatorAccounts {
  user {
    id
    phabricatorAccounts {
      id
      email
      icon
      url
      apiKey
      enabledQueries
    }
  }
}

query ListPhabricatorQueries {
  user {
    id
    phabricatorQueries {
      id
      name
      description
    }
  }
}

mutation CreatePhabricatorAccount($params: PhabricatorAccountParams!) {
  createPhabricatorAccount(params: $params) {
    id
    email
    icon
    url
    apiKey
    enabledQueries
  }
}

mutation DeletePhabricatorAccount($account: ID!) {
  deletePhabricatorAccount(account: $account)
}
