mutation CreateTask($section: ID, $item: ItemParams!) {
  createTask(section: $section, item: $item) {
    ...clientItemFields
  }
}

mutation CreateLink(
  $section: ID
  $item: ItemParams!
  $detail: LinkDetailParams!
  $isTask: Boolean!
) {
  createLink(section: $section, item: $item, detail: $detail, isTask: $isTask) {
    ...clientItemFields
  }
}

mutation EditItem($id: ID!, $item: ItemParams!) {
  editItem(id: $id, item: $item) {
    ...clientItemFields
  }
}

mutation MarkTaskDone($id: ID!, $done: DateTime) {
  markTaskDone(id: $id, done: $done) {
    ...clientItemFields
  }
}

mutation SetTaskController($id: ID!, $controller: TaskController) {
  setTaskController(id: $id, controller: $controller) {
    ...clientItemFields
  }
}

mutation MoveItem($id: ID!, $section: ID, $before: ID) {
  moveItem(id: $id, section: $section, before: $before) {
    ...clientItemFields
  }
}

mutation DeleteItem($id: ID!) {
  deleteItem(id: $id)
}

mutation ArchiveItem($id: ID!, $archived: DateTime) {
  archiveItem(id: $id, archived: $archived) {
    ...clientItemFields
  }
}

mutation SnoozeItem($id: ID!, $snoozed: DateTime) {
  snoozeItem(id: $id, snoozed: $snoozed) {
    ...clientItemFields
  }
}

mutation MarkTaskDue($id: ID!, $due: DateTime) {
  markTaskDue(id: $id, due: $due) {
    ...clientItemFields
  }
}

mutation CreateUser($email: String!, $password: String!, $isAdmin: Boolean) {
  createUser(email: $email, password: $password, isAdmin: $isAdmin) {
    id
  }
}

mutation DeleteUser($id: ID!) {
  deleteUser(id: $id)
}

mutation ChangePassword($currentPassword: String!, $newPassword: String!) {
  changePassword(currentPassword: $currentPassword, newPassword: $newPassword) {
    id
  }
}
