mutation CreateUser($email: String!, $password: String!, $isAdmin: Boolean) {
  createUser(email: $email, password: $password, isAdmin: $isAdmin) {
    id
  }
}

mutation DeleteUser($id: ID!) {
  deleteUser(id: $id)
}

mutation ChangePassword($currentPassword: String!, $newPassword: String!) {
  changePassword(currentPassword: $currentPassword, newPassword: $newPassword) {
    id
  }
}
