query ListContextState($dueBefore: RelativeDateTime!) {
  user {
    id
    email
    isAdmin

    inbox(filter: { isArchived: false, isSnoozed: false, isPending: true }) {
      count
    }

    contexts {
      id
      stub
      name

      dueTasks: items(
        filter: { isArchived: false, isSnoozed: false, dueBefore: $dueBefore }
      ) {
        count
      }

      subprojects {
        id
      }

      projects {
        id
        stub
        name

        dueTasks: items(
          filter: { isArchived: false, isSnoozed: false, dueBefore: $dueBefore }
        ) {
          count
        }

        subprojects {
          id
        }
      }
    }
  }

  problems {
    description
    url
  }

  schemaVersion
}

query PageContent($path: String!) {
  pageContent(path: $path)
}

query ListUsers {
  users {
    id
    email
    isAdmin
  }
}

query ListInbox {
  user {
    inbox {
      items {
        ...clientItemFields
      }
    }
  }
}

query ListTaskList($taskList: ID!) {
  taskList(id: $taskList) {
    items {
      items {
        ...clientItemFields
      }
    }

    sections {
      id
      name

      items {
        items {
          ...clientItemFields
        }
      }
    }
  }
}
