query ListUsers {
  users {
    id
    email
    isAdmin
  }
}

query ListInbox {
  user {
    inbox {
      items {
        ...clientItemFields
      }
    }
  }
}

query ListTaskList($taskList: ID!) {
  taskList(id: $taskList) {
    items {
      items {
        ...clientItemFields
      }
    }

    sections {
      id
      name

      items {
        items {
          ...clientItemFields
        }
      }
    }
  }
}
