query ListPhabricatorAccounts {
  user {
    id
    phabricatorAccounts {
      id
      email
      icon
      url
      apiKey
      enabledQueries
    }
  }
}

query ListPhabricatorQueries {
  user {
    id
    phabricatorQueries {
      queryId
      name
      description
    }
  }
}

mutation CreatePhabricatorAccount($params: CreatePhabricatorAccountParams!) {
  createPhabricatorAccount(params: $params) {
    id
    email
    icon
    url
    apiKey
    enabledQueries
  }
}

mutation UpdatePhabricatorAccount(
  $id: ID!
  $params: UpdatePhabricatorAccountParams!
) {
  updatePhabricatorAccount(id: $id, params: $params) {
    id
    email
    icon
    url
    apiKey
    enabledQueries
  }
}

mutation DeletePhabricatorAccount($account: ID!) {
  deletePhabricatorAccount(account: $account)
}
