query SchemaVersion {
  schemaVersion
}

query ListContextState {
  user {
    id
    email
    isAdmin

    inbox{
      count
    }

    contexts {
      id
      stub
      name

      remainingTasks: items {
        isTask(done: false) {
          count
        }
      }

      subprojects {
        id
      }

      projects {
        id
        stub
        name

        remainingTasks: items {
          isTask(done: false) {
            count
          }
        }

        subprojects {
          id
        }
      }
    }
  }

  problems {
    description
    url
  }
}

query PageContent($path: String!) {
  pageContent(path: $path)
}

query ListUsers {
  users {
    id
    email
    isAdmin
  }
}

query ListInbox {
  user {
    inbox {
      items {
        ...clientItemFields
      }
    }
  }
}

query ListTaskList($taskList: ID!) {
  taskList(id: $taskList) {
    items {
      items {
        ...clientItemFields
      }
    }

    sections {
      id
      name

      items {
        remaining: isTask(done: false) {
          count
        }

        items {
          ...clientItemFields
        }
      }
    }
  }
}
