query ListBugzillaAccounts {
  user {
    id
    bugzillaAccounts {
      id
      name
      icon
      url
      searches {
        id
        name
        type
        query
        dueOffset
        url
      }
    }
  }
}

mutation CreateBugzillaAccount($params: BugzillaAccountParams!) {
  createBugzillaAccount(params: $params) {
    id
    name
    icon
    url
    searches {
      id
      name
      type
      query
      dueOffset
      url
    }
  }
}

mutation DeleteBugzillaAccount($account: ID!) {
  deleteBugzillaAccount(account: $account)
}

mutation CreateBugzillaSearch($account: ID!, $params: BugzillaSearchParams!) {
  createBugzillaSearch(account: $account, params: $params) {
    id
    name
    type
    query
    dueOffset
    url
  }
}

mutation EditBugzillaSearch($id: ID!, $params: BugzillaSearchParams!) {
  editBugzillaSearch(search: $id, params: $params) {
    id
    name
    type
    query
    dueOffset
    url
  }
}

mutation DeleteBugzillaSearch($search: ID!) {
  deleteBugzillaSearch(search: $search)
}
